# Generated by Django 4.1.5 on 2023-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('idaprobacion', models.IntegerField(primary_key=True, serialize=False)),
                ('aprobador', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'aprobacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idsolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
